owner: divtiply
repo: artupptime

sites:
  - name: Christie's
    url: https://www.christies.com/
    expectedStatusCodes: [200]
  - name: Sotheby's
    url: https://www.sothebys.com/en/
    expectedStatusCodes: [200]
  - name: Phillips
    url: https://www.phillips.com/
    expectedStatusCodes: [200]
  - name: Bonhams
    url: https://www.bonhams.com/
    expectedStatusCodes: [200]
  # Requires JS
  # - name: Herritage Auctions
  #   url: https://www.ha.com/
  #   expectedStatusCodes: [200]
  - name: China Guardian
    url: https://www.cguardian.com/en/
    expectedStatusCodes: [200]
  - name: Poly Auction
    url: https://www.polyauction.com.hk/en
    expectedStatusCodes: [200]
  - name: Art Basel
    url: https://www.artbasel.com/
    expectedStatusCodes: [200]

status-website:
  baseUrl: /artupptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: ArtUpptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
